{% set version = "2.8" %}
{% set sha256 = "d15b462b4b19cf40f5cfecf9473211e2802b42380b6e7066f15cb7d5cc154f69" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
  host:
    - libevent
    - ncurses

  run:
    - libevent
    - ncurses

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - dougalsutherland
