{% set version = "3.4" %}
{% set sha256 = "551ab8dea0bf505c0ad6b7bb35ef567cdde0ccb84357df142c254f35a23e19aa" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/releases/download/{{ version }}/tmux-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - patch
    - pkg-config
    - bison

  host:
    - libevent
    - libutf8proc  # [osx]
    - ncurses

  run:
    - libevent
    - ncurses

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - djsutherland
    - dbast
    - matthiasdiener
