{% set version = "3.2a" %}
{% set sha256 = "551553a4f82beaa8dadc9256800bcc284d7c000081e47aa6ecbb6ff36eacd05f" %}

package:
  name: tmux
  version: {{ version }}

source:
  url: https://github.com/tmux/tmux/releases/download/{{ version }}/tmux-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - configure.ac.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - patch
    - pkg-config

  host:
    - libevent
    - ncurses

  run:
    - libevent
    - ncurses

test:
  commands:
    # Verify command existence.
    - which tmux

    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - jakirkham
    - djsutherland
    - dbast
