context:
  version: "3.8"

package:
  name: tmux
  version: ${{ version }}_

source:
  url: https://github.com/tmux/tmux/archive/${{ version }}.tar.gz
  sha256: f873f9379c9cf30d3d66b642a955118c4fbb0019d046d13e6012340811e5dcb7

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - patch
    - pkg-config
    - bison
    - if: unix
      then:
        - gnuconfig
  host:
    - libevent
    - ncurses
    - if: osx
      then:
        - libutf8proc
        - jemalloc
  run:
    - libevent
    - ncurses

tests:
  - script:
      - tmux -V

about:
  homepage: https://tmux.github.io/
  license: ISC
  license_file: COPYING
  summary: A terminal multiplexer.

extra:
  recipe-maintainers:
    - XhstormR
    - jakirkham
    - djsutherland
    - dbast
    - matthiasdiener
    - seowalex
