travis:
  secure:
    BINSTAR_TOKEN: AWuNjcE/Xk4mahlEXO6T3NFPNqJtG6bIkpZNFi957scszyzTQcy4wJ3HHWRvphc9i/05NAHDvRzUdCLNEdK2An/ncamOrqYK+vS06hWrLawrQikoZ+mSXyvQu8Efmnjn3axrEncUnky4ZzZLbw3FmHgXF1NgSv/IPHPFsh4ggA7igqPcpiflDkPI+uGD/9iPAIvrCFnBUp9sg/v37Hh32lC8hEoxgclRGUD1P31Cb/oeByfRJZ7IrrYavBZHXaomCLotTkVrik7FpQYOUhxhJHrOXJPzi02nNMiKM0ZNjUHlqoQF+WYbxUN+LnIDTXbwDbsYghrrbc5HhZOUbCsc7HKtyjG5W1uTKJhTIpaWLfO6m/aLGzWoaOGZg0LSwemCDGO9FdpYM3bLoJKiZ4aBsMntyZyPeoO6x6X9AwFpqF1PcMG19d4KhaeTy+553G30NJ0baS3bqiRfFJRFmQN6VlN4vGp2ESXow6rAJ2EMl8IQM4tUt2RdHSpbL0O9sIUnNE6cSxLSPudT/tGV0t8+26hiGGVvX/dgnnYTkSCqzDc7gtZBZOj5ujF1FQ9wL1kFQAVCftojqMO674FFcj490Mp6HzbuT1IFgmN/9f8K75WxK7DWlbweJfSnGgv+4GlPTRwlDMFK9/vaOhxQKljAGw3V6A3GZHX9kF0Wr/6BLEU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
